
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mysensei.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Chat
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Chat()
    {

        this.LogChatRead = new HashSet<LogChatRead>();

    }


    public int Id { get; set; }

    public string Message { get; set; }

    public int PersonId { get; set; }

    public int ChatRoomId { get; set; }

    public System.DateTime DateCreated { get; set; }



    public virtual Person Person { get; set; }

    public virtual ChatRoom ChatRoom { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LogChatRead> LogChatRead { get; set; }

}

}
