
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mysensei.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Course
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Course()
    {

        this.Active = true;

        this.Student = new HashSet<Person>();

        this.Tag = new HashSet<Tag>();

        this.Rating = new HashSet<Rating>();

        this.ChatRoom = new HashSet<ChatRoom>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public int PersonId { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public bool Active { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }



    public virtual Person Teacher { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Person> Student { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tag> Tag { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rating> Rating { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChatRoom> ChatRoom { get; set; }

}

}
