
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mysensei.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LocationGroup
{

    public int Id { get; set; }

    public string Name { get; set; }

    public Nullable<short> ZipcodeStart { get; set; }

    public Nullable<short> ZipcodeEnd { get; set; }

}

}
