
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mysensei.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LogChatRead
{

    public int Id { get; set; }

    public System.DateTime DateCreated { get; set; }

    public int PersonId { get; set; }

    public int ChatId { get; set; }



    public virtual Person Person { get; set; }

    public virtual Chat Chat { get; set; }

}

}
