

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mysensei.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class mysenseiCTXContainer : DbContext
{
    public mysenseiCTXContainer()
        : base("name=mysenseiCTXContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Person> PersonSet { get; set; }

    public virtual DbSet<Course> CourseSet { get; set; }

    public virtual DbSet<Tag> TagSet { get; set; }

    public virtual DbSet<LocationCity> LocationCitySet { get; set; }

    public virtual DbSet<LocationGroup> LocationGroupSet { get; set; }

    public virtual DbSet<Rating> RatingSet { get; set; }

    public virtual DbSet<Administrator> AdministratorSet { get; set; }

    public virtual DbSet<TagGroup> TagGroupSet { get; set; }

    public virtual DbSet<Chat> ChatSet { get; set; }

    public virtual DbSet<ChatRoom> ChatRoomSet { get; set; }

    public virtual DbSet<LogChatRead> LogChatReadSet { get; set; }

}

}

